
name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:  
      SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL }} 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Slack Notification
      uses: acti0ns/slack@v1
      with:
        status: ${{job.status}}
        steps: ${{toJson(steps)}}
        channel: '#cicd-pipeline-projectr'
      if: always()  
    
    

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        

    - name: Run tests
      run: |
        python -m unittest discover -p "*_test.py"

  deploy:
    runs-on: ubuntu-latest

    needs: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        

    - name: Deploy to staging
      run: |
     
        echo "Deploying to staging environment"

        
        
